# _____ _          _   ______    _                _
# |  __ (_)        | | |  ____|  (_)              | |
# | |__) |__  _____| | | |__ _ __ _  ___ _ __   __| |___
# |  ___/ \ \/ / _ \ | |  __| '__| |/ _ \ '_ \ / _` / __|
# | |   | |>  <  __/ | | |  | |  | |  __/ | | | (_| \__ \
# |_|   |_/_/\_\___|_| |_|  |_|  |_|\___|_| |_|\__,_|___/
#

mysql:
  jdbc-url: jdbc:mysql://[host]:[port]/[db]?autoReconnect=true
  host: localhost
  port: 3306
  username: root
  password: password
  database: rRFTB
  tables:
    players: playerData
    friends: friendsData
    requests: requestsData
    settings: settingsData
settings:
  modify-msg-command: true
  modify-tell-command: true
  showExtraLogs: false
  dateFormat:
    today: 'Today at <todayFormat>'
    todayFormat: 'HH:mm'
    other-day: 'dd/MM/yy'
  blacklist-go-command-servers:
    - 'AuthServer1'
    - 'AuthServer2'
  servers-replacers:
    - 'Hub1:Hub'
    - 'Hub2:Hub'
    - 'Hub3:Hub'
    - 'AuthServer:Portal Gate'

