name: CookieFriends
version: ${project.version}
main: dev.mruniverse.cookiefriends.SpigotFriends
api-version: 1.16
authors: [ MrUniverse44, Sebastnchann ]
description: Simple Friends Plugin
website: rigox.club
